services:
  blogweb:
    build:
      context: ..
      dockerfile: Dockerfile.web
    image: jingz-blog-web:latest
    container_name: jingz-blog-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      SITE_URL: https://www.zovoj.ink
      NEXT_PUBLIC_ADMIN_EMAILS: 918939601@qq.com
      AUTH_SECRET: Ay/CXMw4OLFLvFazkah8nNEvYUURD5iPtFijvZBvf5o=
      AUTH_TRUST_HOST: "true"
      AUTH_URL: https://www.zovoj.ink
      NEXTAUTH_URL: https://www.zovoj.ink
      AUTH_GITHUB_ID: Ov23librUscjPsoLlnto
      AUTH_GITHUB_SECRET: e0c518c4eec2e68528c28bb88f522e1a43605296
      NEXT_PUBLIC_GO_API_BASE: /goapi
      GO_API_BASE: http://jingz-blog-api:8080
      REVALIDATE_SECRET: b671528b34a117f04edda6bfa1ac443e4672f8b5d34d5455b054cd03852ccea7
      UPLOADTHING_TOKEN: eyJhcGlLZXkiOiJza19saXZlXzNlZDJiYWZlNTIyOWUyNjQ3ZWIzYmI5MDM2N2VlZTk5Y2YzZTFkMTdmODMxNTE3Y2M4MWVhZjJhMjUzZDRkMzUiLCJhcHBJZCI6IjFnZG4xc2xpOW0iLCJyZWdpb25zIjpbInNlYTEiXX0=
      DATABASE_URL: postgresql://neondb_owner:npg_VbBRHvSt4nu1@ep-cool-frost-adz6a2gp-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
