// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Echo struct {
	Id          int64  `json:"id"`
	Reference   string `json:"reference"`
	Content     string `json:"content"`
	IsPublished bool   `json:"isPublished"`
	CreatedAt   string `json:"createdAt"`
}

type EchoCreateReq struct {
	Reference   string `json:"reference"`
	Content     string `json:"content"`
	IsPublished bool   `json:"isPublished"`
}

type EchoDeleteReq struct {
	Id int64 `path:"id"`
}

type EchoListReq struct {
	Query    string `form:"query,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type EchoListResp struct {
	Items    []Echo `json:"items"`
	Total    int64  `json:"total"`
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
}

type EchoToggleReq struct {
	Id          int64 `path:"id"`
	IsPublished bool  `json:"isPublished"`
}

type EchoUpdateReq struct {
	Id          int64  `path:"id"`
	Reference   string `json:"reference"`
	Content     string `json:"content"`
	IsPublished bool   `json:"isPublished"`
}
