// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type NoteTag struct {
	Id      int64  `json:"id"`
	TagName string `json:"tagName"`
	TagType string `json:"tagType"`
}

type Note struct {
	Id          int64      `json:"id"`
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	Content     string     `json:"content"`
	IsPublished bool       `json:"isPublished"`
	CreatedAt   string     `json:"createdAt"`
	Tags        []NoteTag  `json:"tags,omitempty"`
}

type NoteCreateReq struct {
	Slug            string   `json:"slug"`
	Title           string   `json:"title"`
	Content         string   `json:"content"`
	IsPublished     bool     `json:"isPublished"`
	RelatedTagNames []string `json:"relatedTagNames,optional"`
}

type NoteDeleteReq struct {
	Id int64 `path:"id"`
}

type NoteListReq struct {
	Query    string `form:"query,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type NoteListResp struct {
	Items    []Note `json:"items"`
	Total    int64  `json:"total"`
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
}

type NoteToggleReq struct {
	Id          int64 `path:"id"`
	IsPublished bool  `json:"isPublished"`
}

type NoteUpdateReq struct {
	Id              int64    `path:"id"`
	Slug            string   `json:"slug,optional"`
	Title           string   `json:"title,optional"`
	Content         string   `json:"content,optional"`
	IsPublished     bool     `json:"isPublished,optional"`
	RelatedTagNames []string `json:"relatedTagNames,optional"`
}
