// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Tag struct {
	Id      int64  `json:"id"`
	TagName string `json:"tagName"`
	TagType string `json:"tagType"`
}

type TagListReq struct {
	TagType string `form:"tagType,optional"`
}

type TagCreateReq struct {
	TagName string `json:"tagName"`
	TagType string `json:"tagType"`
}

type TagUpdateReq struct {
	Id      int64  `path:"id"`
	TagName string `json:"tagName"`
}

type TagDeleteReq struct {
	Id int64 `path:"id"`
}
