// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	ai "server/blogapi/internal/handler/ai"
	blog "server/blogapi/internal/handler/blog"
	echo "server/blogapi/internal/handler/echo"
	note "server/blogapi/internal/handler/note"
	tag "server/blogapi/internal/handler/tag"
	weather "server/blogapi/internal/handler/weather"
	"server/blogapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/blogs",
				Handler: blog.BlogListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/blogs",
				Handler: blog.BlogCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/blogs/:id",
				Handler: blog.BlogUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/blogs/:id",
				Handler: blog.BlogDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/blogs/:id/publish",
				Handler: blog.BlogToggleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/blogs/:slug",
				Handler: blog.BlogDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/blogs/:slug/html",
				Handler: blog.BlogDetailHtmlHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/echos",
				Handler: echo.EchoListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/echos",
				Handler: echo.EchoCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/echos/:id",
				Handler: echo.EchoUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/echos/:id",
				Handler: echo.EchoDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/echos/:id/publish",
				Handler: echo.EchoToggleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/echos/published",
				Handler: echo.EchoPublishedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/notes",
				Handler: note.NoteListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notes",
				Handler: note.NoteCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notes/published",
				Handler: note.NotePublishedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notes/:slug",
				Handler: note.NoteDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notes/:slug/html",
				Handler: note.NoteDetailHtmlHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/notes/:id",
				Handler: note.NoteUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/notes/:id",
				Handler: note.NoteDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/notes/:id/publish",
				Handler: note.NoteToggleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tags",
				Handler: tag.TagListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tags",
				Handler: tag.TagCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tags/:id",
				Handler: tag.TagUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tags/:id",
				Handler: tag.TagDeleteHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/location",
				Handler: weather.LocationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/weather",
				Handler: weather.WeatherHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/weather/info",
				Handler: weather.WeatherInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ai/ask",
				Handler: ai.AskAiHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
