// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	echoFieldNames          = builder.RawFieldNames(&Echo{}, true)
	echoRows                = strings.Join(echoFieldNames, ",")
	echoRowsExpectAutoSet   = strings.Join(stringx.Remove(echoFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	echoRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(echoFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	echoModel interface {
		Insert(ctx context.Context, data *Echo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Echo, error)
		Update(ctx context.Context, data *Echo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEchoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Echo struct {
		Id          int64     `db:"id"`
		Reference   string    `db:"reference"`
		IsPublished bool      `db:"isPublished"`
		Content     string    `db:"content"`
		CreatedAt   time.Time `db:"createdAt"`
	}
)

func newEchoModel(conn sqlx.SqlConn) *defaultEchoModel {
	return &defaultEchoModel{
		conn:  conn,
		table: `"public"."Echo"`,
	}
}

func (m *defaultEchoModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEchoModel) FindOne(ctx context.Context, id int64) (*Echo, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", echoRows, m.table)
	var resp Echo
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEchoModel) Insert(ctx context.Context, data *Echo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, echoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Reference, data.IsPublished, data.Content, data.CreatedAt)
	return ret, err
}

func (m *defaultEchoModel) Update(ctx context.Context, data *Echo) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, echoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Reference, data.IsPublished, data.Content, data.CreatedAt)
	return err
}

func (m *defaultEchoModel) tableName() string {
	return m.table
}
